name: Update GitHub Stats and Date

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Stats and Date
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TZ="Asia/Riyadh"
          CURRENT_DATE=$(date +"%a %b %d %H:%M:%S KSA %Y")
          echo "NEW_DATE=$CURRENT_DATE" >> $GITHUB_ENV
          
          REPOS=$(curl -s -H "Authorization: Bearer $GH_TOKEN" "https://api.github.com/users/${{ github.repository_owner }}" | jq '.public_repos')
          echo "REPOS_COUNT=$REPOS" >> $GITHUB_ENV
          
          COMMITS=$(curl -s -H "Authorization: Bearer $GH_TOKEN" -H "Accept: application/vnd.github.cloak-preview" "https://api.github.com/search/commits?q=author:${{ github.repository_owner }}" | jq '.total_count')
          echo "COMMITS_COUNT=$COMMITS" >> $GITHUB_ENV

      - name: Update SVG File
        run: |
          sed -i "s/TODAY_DATE/${{ env.NEW_DATE }}/g" neofetch-info.svg
          sed -i "s/REPO_COUNT/${{ env.REPOS_COUNT }}/g" neofetch-info.svg
          sed -i "s/COMMIT_COUNT/${{ env.COMMITS_COUNT }}/g" neofetch-info.svg

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add neofetch-info.svg
          git diff-index --quiet HEAD || git commit -m "⏱️ Auto-update GitHub Stats and Date [Skip CI]"
          git push
